artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/SanjuShusanth/ML-Projects/raw/main/updated_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion